### ISSUE TITLE
Feature Request - Ability to fallback to cookies instead of InMemory

### ISSUE THREAD

**Issue by crob** [MikaAK/angular-safeguard#16]

**Comment by bisubus** [comment]
+1, that would be great. `defaultDriverType` looks like ordinary driver type, it falls back to DRIVERS.MEMORY in `useDriver` anyway.

I guess that providing a set of drivers in the order of their preference ([like in localForage](https://localforage.github.io/localForage/#settings-api-setdriver)) would solve the issue.
