### ISSUE TITLE
Error encountered resolving symbol values statically. Function calls are not supported.

### ISSUE THREAD

**Issue by elranu** [MikaAK/angular-safeguard#22]
Hi,
I'm getting this error:

`Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule`

this are my dependencies:
```
 "dependencies": {
        "@angular/common": "2.2.3",
        "@angular/compiler": "2.2.3",
        "@angular/core": "2.2.3",
        "@angular/forms": "2.2.3",
        "@angular/http": "2.2.3",
        "@angular/platform-browser": "2.2.3",
        "@angular/platform-browser-dynamic": "2.2.3",
        "@angular/router": "3.2.3",
        "angular2-locker": "^0.5.0",
        "bootstrap-sass": "^3.3.7",
        "core-js": "^2.4.1",
        "firebase": "^3.5.3",
        "lodash": "^4.16.6",
        "ng2-bootstrap": "^1.1.16",
        "rxjs": "5.0.0-beta.12",
        "ts-helpers": "^1.1.1",
        "zone.js": "^0.6.23"
    },
    "devDependencies": {
        "@types/jasmine": "2.5.38",
        "@types/lodash": "^4.14.38",
        "@types/node": "^6.0.42",
        "@angular/compiler-cli": "2.2.3",
        "angular-cli": "1.0.0-beta.22-1",
        "codelyzer": "~2.0.0-beta.1",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.2.0",
        "karma-chrome-launcher": "^2.0.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-remap-istanbul": "^0.2.1",
        "protractor": "4.0.9",
        "ts-node": "1.2.1",
        "tslint": "^4.0.2",
        "typescript": "~2.0.3",
        "webdriver-manager": "10.2.5"
    }
```

Any idea how to fix it?

**Comment by moxival** [comment]
I think this error is caused by this line of code https://github.com/MikaAK/angular2-locker/blob/master/src/Locker.module.ts#L12

I got around it 

```typescript
@NgModule({
  ...
})
export class SharedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule : SharedModule,
      providers: [
        { provide : LockerConfig, useFactory: lockerConfigFactory },
        Locker
      ]
    };
  }
}
export function lockerConfigFactory() {
  return new LockerConfig('namespace', Locker.DRIVERS.LOCAL);
}
```

But then i have this error:
```
ERROR in members.hasOwnProperty is not a function, resolving symbol SharedModule.forRoot in C:/.../shared.module.ts, resolving symbol AppModule in C:/.../app.module.ts, resolving symbol AppModule in C:/.../app.module.ts
```

If i remove angular2-locker everything works.

I think that this library is not AOT ready and angular-cli beta.22+ requires everything to be AOT ready even if you don't use AOT.

**Comment by WittBulter** [comment]
the same problem

**Comment by jmar87** [comment]
I am getting the same error as moaxial. Using cli beta.24, angular 2.3.1 libs.

**Comment by MikaAK** [comment]
Will fix with new version!

**Comment by WittBulter** [comment]
i love u！！

**Comment by MikaAK** [comment]
Would someone check with the current version of master to see if this still happens? Will be publishing soon just trying to get some other updates in with the new release

**Comment by thekalinga** [comment]
Used npm link & this is the error I'm getting

`ERROR in LockerModule is not an NgModule`

**Comment by thekalinga** [comment]
@MikaAK Any idea why this might be the case?

**Comment by MikaAK** [comment]
Check now @thekalinga it seems to work for me. AoT still doesn't work but I'm still working on that

**Comment by thekalinga** [comment]
@MikaAK For some reason, It is not working for me with `angular-safeguard` `1.0.0` aswell

**Comment by thekalinga** [comment]
1. Reinstalled angular cli `angular-cli@latest`
2. Created a new project using cli
3. Imported `LockerModule`

```typescript
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    LockerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
4. Started & got this error in console
`ERROR in LockerModule is not an NgModule`
