### ISSUE TITLE
Name change to angular-safeguard

### ISSUE THREAD

**Issue by MikaAK** [MikaAK/angular-safeguard#25]
## `angular2-locker` -> `angular-safeguard`

I just wanted to post an issue regarding the changing the name of this library. It is officially unadvised to use angular2 in the name of packages and when it moves to angular3/4 it will become confusing. As angular-locker is already existing and for angular1 I have decided to rename to angular-safeguard!

**Comment by VuongN** [comment]
Now it makes sense on the name change.  Do you have a plan for rollout/upgrade?

**Comment by MikaAK** [comment]
I'm going to deprecate the other package and point to this one
