### ISSUE TITLE
Support of new version angular and angular-cli

### ISSUE THREAD

**Issue by dmitriirudakov** [MikaAK/angular-safeguard#26]
@MikaAK I'm using yours plugin version 1.0.0
I have angular-cli application ("angular-cli": "1.0.0-beta.26", "@angular/core": "^2.4.5") and when I try to compile app with `ng serve` I see an error below:

`ERROR in Error encountered resolving symbol values statically. Calling function 'LockerModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ./src/app/app.module.ts, resolving symbol AppModule ./src/app/app.module.ts`

Looks that it happens because plugin doesn't support AoT compilation and doesn't create metadata.json file.

Could you fix it, please?

**Comment by VuongN** [comment]
For what it's worth, there's a pending issue (https://github.com/MikaAK/angular-safeguard/issues/24) that @MikaAK is working on for next release.  Perhaps it will resolve existing AoT issues.

**Comment by MikaAK** [comment]
Closing as unproductive. @dmitriirudakov  please look through other issues next time first.
