### ISSUE TITLE
Rollup pluggin compatible 

### ISSUE THREAD

**Issue by tuliogalli** [MikaAK/angular-safeguard#27]
Hello,

Thanks for component, very helpful, and congratulations on the last update (1.0.0).

I installed the "rollup" component (https://github.com/rollup/rollup)
I do not know if I did everything right, but I do not think it's compatible with your plugin.
It displays this error message.

> Rollup failed: 'Locker' is not exported by node_modules / angular-safeguard / dist / locker.js (imported by
>              Src / providers / client.service.ts). For help fixing this error see
>              Https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
> 

To configure the component follow these steps:

Https://www.bountysource.com/issues/36339429-feature-request-ionic-2-dev-prod-environment-variables-configuration

Are you able to adapt your component so that it is compatible? Can I wait for this?

Thank you

**Comment by MikaAK** [comment]
I'm going to release the code with es6 and es6 builds so it's possible to rollup proper! I'll finish it this weekend

**Comment by MikaAK** [comment]
@tuliogallie try this in the meantime https://github.com/rollup/rollup-plugin-commonjs

**Comment by tuliogalli** [comment]
thank you dude
