### ISSUE TITLE
ERROR in LockerModule is not an NgModule

### ISSUE THREAD

**Issue by Octopixell** [MikaAK/angular-safeguard#29]
First of all, thanks for making this amazing component! I love using it.

There's one problem I'm getting though. I'm using this component in a project created with Angular CLI and when I use `ng serve` to start up the dev server. I get the following error:

```
ERROR in LockerModule is not an NgModule
webpack: Failed to compile.
```

The output of my `ng --version` command:

```
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.25.5]
node: 6.9.4
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
```

I'm not sure what I'm doing wrong, I've tried re-installing the package but that didn't help either. As I'm not seeing anybody else with this issue on here I think I must be doing something wrong..

Anybody have an idea? Thanks!

**Comment by MikaAK** [comment]
Probably related to #24, you can try using master, tests need to be updated then i can publish

**Comment by Octopixell** [comment]
Hi Mika,

Sorry for the late reply! Stupid question; How do I go about using the master branche? Just using `angular-safeguard@latest`? 

Thanks again

**Comment by TxOne** [comment]
ERROR in Error encountered resolving symbol values statically. Calling function
'LockerModule', function calls are not supported. Consider replacing the functio
n or lambda with a reference to an exported function, resolving symbol AppModule

**Comment by Octopixell** [comment]
I'm having the same issue as @TxOne now. @MikaAK can we try and figure out what is going wrong here together? 😄 

Thanks!

**Comment by MikaAK** [comment]
you would have to go into package.json and point to `angular-safeguard: "mikaak/angular-safeguard"` I haven't had time to fix tests but as soon as it's done I'll release :(

**Comment by Octopixell** [comment]
@MikaAK I just tried setting `"angular-safeguard": "mikaak/angular-safeguard"` in my `package.json` and then running npm update but that results in a `Module not found: Error: Can't resolve 'angular-safeguard'` error.

I'm probably doing something wrong here.. But the fact that AoT compilation doesn't work is a real issue here. 😞  

Thanks anyways!

**Comment by MikaAK** [comment]
@Octopixell `"angular-safeguard": "git://github.com/mikaak/angular-safeguard.git`
From NPM docs

**Comment by MikaAK** [comment]
@Octopixell are you using yarn? I ran into someone who was getting these messages when using yarn to install, but not when using npm

**Comment by Octopixell** [comment]
@MikaAK nope we're using NPM for all our packages.

**Comment by MikaAK** [comment]
Ok good to know, was just something I heard of but I'll look into this more. I've been working at 3 jobs currently as such no time to do anything. One of them ends in a month however so I should get a chance to take a look then. Or if i get any spare time this is next on my list

**Comment by Octopixell** [comment]
@MikaAK I suppose I could use `master` if that's stable at the moment :)

**Comment by wewo** [comment]
@MikaAK so what is the progress in solving AoT with this module?

I had no success in following your steps.

`"angular-safeguard": "mikaak/angular-safeguard",` in `package.json`
I get `npm ERR! fatal: Could not read from remote repository.`

Latest version from npm (1.0.1) doesn't work with AoT. Thanks

**Comment by Octopixell** [comment]
@MikaAK using `"angular-safeguard": "git://github.com/mikaak/angular-safeguard.git"` in my `package.json` does not actually fix anything. It actually just breaks things that much more. Check the following error:

```
ERROR in ./src/app/services/apps.service.ts
Module not found: Error: Can't resolve 'angular-safeguard' in '/Users/marco/dashboard/src/app/services'
 @ ./src/app/services/apps.service.ts 12:0-43
 @ ./src/app/apps/apps.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:4200/ ./src/main.ts
```

**Comment by Octopixell** [comment]
Just realised that this happens because the module isn't being built since it's not installed by NPM(?). Maybe I'm wrong though.. In any case, I'm getting into some serious trouble now since I was supposed to launch today.

**Comment by Octopixell** [comment]
Building the module by hand results in the following:

```
Marcos-MacBook-Pro:angular-safeguard marco$ npm run build

> angular-safeguard@1.0.0 build /Users/marco/dashboard/node_modules/angular-safeguard
> NODE_ENV='production' webpack --progress && rm -rf ./dist/test

Hash: 50b55294f53c015f869e             
Version: webpack 2.3.3
Time: 986ms

ERROR in Could not resolve "/Users/marco/dashboard/node_modules/angular-safeguard/src/Locker.module.ts" from "/Users/marco/dashboard/node_modules/angular-safeguard/src/Locker.module.ts".

ERROR in Entry module not found: Error: Can't resolve './src/index.ts' in '/Users/marco/dashboard/node_modules/angular-safeguard'

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/marco/.nvm/versions/node/v6.9.4/bin/node" "/Users/marco/.nvm/versions/node/v6.9.4/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-safeguard@1.0.0 build: `NODE_ENV='production' webpack --progress && rm -rf ./dist/test`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-safeguard@1.0.0 build script 'NODE_ENV='production' webpack --progress && rm -rf ./dist/test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-safeguard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV='production' webpack --progress && rm -rf ./dist/test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-safeguard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-safeguard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marco/dashboard/node_modules/angular-safeguard/npm-debug.log

```

Is `master` really up to date? Or do you still have local changes?

**Comment by maytis** [comment]
This error is still present. I have tried building from master branch too. When is the release expected ?
![screen shot 2017-04-25 at 5 29 17 pm](https://cloud.githubusercontent.com/assets/5130490/25384134/c233b830-29dc-11e7-80f4-57f03c2ddd37.png)

**Comment by Octopixell** [comment]
Unfortunately, it seems not very soon. Mika however said this would be the case in this comment: https://github.com/MikaAK/angular-safeguard/issues/29#issuecomment-288554975 

I have already switched over to another package as I had to launch the app before a certain deadline. Not so happy about that as I'd rather have used angular-safeguard. My knowledge of making modules and packages for Angular2 isn't good enough, otherwise I'd have done a pull request or something similar.

**Comment by maytis** [comment]
Thanks for the replay Octopixell. I'm in a similar situation. May I know what package you have used.

**Comment by Octopixell** [comment]
@maytis In order to launch our app we had to resort to this package: https://www.npmjs.com/package/angular2-cool-storage

**Comment by MikaAK** [comment]
sorry guys, i've had a contract that's been really pressing. It's due this weekend so I'll have some time afterwords :)

**Comment by amitgaur208** [comment]
@MikaAK  I am facing the same issue. Please help or i need to remove this module

**Comment by Octopixell** [comment]
Hey @MikaAK have you gotten the chance to get into this now? I'm starting a new project right now and would love to use your module over any other stuff. Thanks!

**Comment by thekalinga** [comment]
This issue is pending from Feb on. @MikaAK Why don't you release the module without the test cases?

You can work on them when you get time rather than letting this issue affect everyone who is using this module

**Comment by outsideMyBox** [comment]
Hi @MikaAK,

any news on this issue? It's also blocking me (I also tried using the master branch without success).

**Comment by Magnusri** [comment]
Same issue here.. Any fixes by now? 📦

**Comment by Octopixell** [comment]
Unfortunately no - @MikaAK if you want to drop support for this package, please let us know so we can all move on. Just please don't keep us all in the dark? Thanks!

**Comment by Magnusri** [comment]
I have also moved to 
https://www.npmjs.com/package/angular2-cool-storage

At least for now,

**Comment by demetrio812** [comment]
guys I've lost hopes in this project...probably better to stop waiting and help building other projects that are actually maintained...

**Comment by MikaAK** [comment]
@demetrio812 how bout some PR's instead of that sass eh? I'm working 3 jobs right now and have no time for this. I have stated if someone can do a pr I will do support. Once 2 if my jobs end ill do it myself however

**Comment by demetrio812** [comment]
@MikaAK what ppl asked was a reply, just talking sometimes really help building a community around a project, some ppl already asked to support the project given that you don't have the time...

However, if I will need it and don't find something better, I'll do it, but the fact that you don't even have time to answer (or just to do a temp release) will also mean you may not even the time to review a PR

I understand it's not easy to maintain it while you have to prioritise work, but I can see from this conversation that many ppl are willing to help, if they are allowed to
