### ISSUE TITLE
Always use SESSION Storage , Cant able to set LOCAL or COOKIE

### ISSUE THREAD

**Issue by Pondernew** [MikaAK/angular-safeguard#32]
I tried to change configuration and also
this.locker.useDriver(DRIVERS.LOCAL);
    this.locker.set('auth_key', data.json().Token );
-------------------------------------------------------------
 this.locker.set(DRIVERS.LOCAL,'auth_key', data.json().Token );

Both didn't work for me.

**Comment by MikaAK** [comment]
Good to know, are you using AoT did it work with it? I will try and update soon. My contract is done in 2 weeks so I'll be able to update this then. (PR's welcome I always have time to merge those in)

**Comment by alexandernst** [comment]
I'm having the same issue. No matter how/what I do, all my data end's up saved in the sessionStorage.

**Comment by amitgaur208** [comment]
@MikaAK Drivers fallback also not working

**Comment by szantogeri** [comment]
+1

**Comment by outsideMyBox** [comment]
You need to add 
`defaultDriverType: DRIVERS.LOCAL,`
in your lockerConfig.
