### ISSUE TITLE
Allow Angular4

### ISSUE THREAD

**Issue by alexandernst** [MikaAK/angular-safeguard#33]
Since Angular 4 didn't break anything in this library can the package.json be tweaked so it can allow Angular4?

**Comment by MikaAK** [comment]
What version are you on?

**Comment by alexandernst** [comment]
4.0.0

**Comment by alexandernst** [comment]
Just to put a little bit more of context/documentation: https://angular-update-guide.firebaseapp.com/

**Comment by MikaAK** [comment]
Done in v1.0.2, publishing isn't working from my hotel... I'll have to do it Saturday

**Comment by maytis** [comment]
MikaAK, will this release fix the error "LockerModule is not a NgModule". Also, does it support AOT.
