### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by alexandernst** [MikaAK/angular-safeguard#34]
I get this when I try to use `LockerModule.withConfig()`:

    ERROR in Error encountered resolving symbol values statically. Calling function 'LockerModule',
    function calls are not supported. Consider replacing the function or lambda with a reference to an
    exported function, resolving symbol LocalStorage in ..../ng2-demo/src/app/app.local-storage.ts,
    resolving symbol AppModule in ..../ng2-demo/src/app/app.module.ts, resolving symbol AppModule
    in ..../ng2-demo/src/app/app.module.ts
    webpack: Failed to compile.

The problem doesn't appear if I try to use `LockerModule` without calling `withConfig()`.

**Comment by Octopixell** [comment]
Likely related to #29 as this seems to be the same error but different function. The module doesn't seem to publish its metadata to Angular and therefor it cannot run any AoT compiling

**Comment by Octopixell** [comment]
Oh, and #24 not to forget.
