### ISSUE TITLE
Create `dist` directory in master branch

### ISSUE THREAD

**Issue by tabe1hands** [MikaAK/angular-safeguard#36]
It's useful to install the latest source with github commit ID like the following:
```
{
  ...
  "dependencies": {
    ...
    "angular-safeguard": "https://github.com/MikaAK/angular-safeguard.git#4a3d9f0",
    ...
  }
}
```
I'd like to use the latest source because it supports AoT.

**Comment by MikaAK** [comment]
unfortunately keeping dist in src code is really painful and leads to bugs
