### ISSUE TITLE
Compatibility with angular-locker when using hybrid app

### ISSUE THREAD

**Issue by robscotts4rb** [MikaAK/angular-safeguard#38]
The previous version that was called `angular2-locker` worked great with `angular-locker` as you could configure the settings to store things under the same namespace.

Now with the change to store things as `{ data: myObj }` we can no longer read things stored using `angular-locker` because they aren't in the expected format. 

It would be nice if `angular-safeguard` can read properties that are stored as simple values (strings, numbers, etc) and the new advanced format.

Happy to provide a pull request if needs be

**Comment by MikaAK** [comment]
Pull requests are much welcomed! Going to try and get the new version all fixed up tomorrow during my flight.

**Comment by MikaAK** [comment]
I'm going to close this as it's not really a priority. If a PR is submitted I will merge it in :)
