### ISSUE TITLE
Bug in getting FALSE value

### ISSUE THREAD

**Issue by knafteN** [MikaAK/angular-safeguard#42]
**Problem description:**
- Use PolyfillDriver
- Save value: `this.storage.set(DRIVERS.SESSION, 'foobar', false);`
- Get value: `const result = this.storage.get(DRIVERS.SESSION, 'foobar');`

**Expectation**
- the value `result` equals `false`

**Actual behaviour**
- the value `result` equals `{ data: false }`

**Analysis**
- see: https://github.com/MikaAK/angular-safeguard/blob/1ba38daf6e778dddb10df35ce4780bcc5fe683e0/src/PolyfillDriver.ts#L21
- the condition `&& data.data` returns false for **ALL FALSY** JavaScript values

**Possible solution**
- maybe it would be better to use `if (data && data.hasOwnProperty('data'))`

**Comment by MikaAK** [comment]
Good catch, a PR would be welcome but I can try to fix this next weekend
